#!/usr/bin/env python3
"""Trigger one CCT generation job from this box (option B of the 2026-09-02 issue).

The four reports are generated by POST /api/v1/jobs/trigger with a triggerMode,
which is what `.github/workflows/trading-system.yml` has been doing on a GitHub
Actions `schedule:`. Actions `schedule:` is best-effort and its start time has
no bound (measured +10.1 h on 2026-08-28), which is the whole reason the issue
exists. This trigger runs from the same nullclaw cron that reads the reports,
so the producer and the consumer share one clock and one reliability domain.

The mode names mirror trading-system.yml's `Determine Analysis Type` step.

Usage:
  tools/trigger-cct-job.py pre-market            # 12:30 UTC weekdays
  tools/trigger-cct-job.py intraday              # 16:00 UTC weekdays
  tools/trigger-cct-job.py eod                   # 20:05 UTC weekdays
  tools/trigger-cct-job.py weekly                # 14:00 UTC Sunday
  tools/trigger-cct-job.py --dry-run pre-market  # print what it would POST

Exit: 0 on success:true, 1 on anything else (the cron jobs verify exit_only,
non-zero makes the operator alert fire).
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.request

BASE = os.environ.get("CCT_BASE", "https://tft-trading-system.yanggf.workers.dev")
# Same UA family as crates/cct/src/api.rs — the WAF 403s urllib's default.
USER_AGENT = "nullclaw-cct/1.0"

MODES = {
    "pre-market": "morning_prediction_alerts",
    "intraday": "midday_validation_prediction",
    "eod": "next_day_market_prediction",
    "weekly": "weekly_review_analysis",
}


def api_key() -> str:
    path = os.environ.get("CLAW_CONFIG") or os.path.expanduser("~/.nullclaw/config.json")
    try:
        with open(path, encoding="utf-8") as fh:
            cfg = json.load(fh)
        key = cfg.get("cct", {}).get("api_key")
        if isinstance(key, str) and key:
            return key
    except Exception:
        pass
    return "yanggf"  # public routing token, same fallback as the skill


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("mode", choices=sorted(MODES),
                    help="which generation job to trigger")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--timeout", type=int, default=600,
                    help="the trigger POST returns only when the job finishes")
    args = ap.parse_args()

    trigger_mode = MODES[args.mode]
    url = f"{BASE.rstrip('/')}/api/v1/jobs/trigger"
    body = json.dumps({"triggerMode": trigger_mode}).encode()

    if args.dry_run:
        print(f"POST {url} X-API-KEY={api_key()!r} User-Agent={USER_AGENT} "
              f"X-Trigger-Source=nullclaw-cron body={body!r}")
        return 0

    req = urllib.request.Request(
        url, data=body, method="POST",
        headers={
            "Content-Type": "application/json",
            "X-API-KEY": api_key(),
            "X-Trigger-Source": "nullclaw-cron",
            "User-Agent": USER_AGENT,
        })
    try:
        with urllib.request.urlopen(req, timeout=args.timeout) as resp:
            payload = json.load(resp)
    except urllib.error.HTTPError as e:
        print(f"⚠️ cct trigger {args.mode} failed: HTTP {e.code}")
        return 1
    except (urllib.error.URLError, OSError, json.JSONDecodeError) as e:
        print(f"⚠️ cct trigger {args.mode} failed: {e}")
        return 1

    ok = payload.get("success") is True
    data = payload.get("data") or {}
    if ok:
        print(f"✅ cct {args.mode} triggered ({trigger_mode}) "
              f"run={data.get('run_id') or data.get('execution_id') or 'ok'}")
        return 0
    print(f"⚠️ cct trigger {args.mode} answered success=false: "
          f"{str(payload)[:200]}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
